<a href="https://colab.research.google.com/github/electrojam/Breast-cancer-with-96-accuracy/blob/main/Clase6_Broadcasting_y_Operaciones_L%C3%B3gicas_en_NumPy6_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Brodadcasting

In [2]:
import numpy as np

In [4]:
# numpy extiende array discount para multiplicarlo por array prices
prices = np.array([100, 200, 300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [5]:
# numpy extiende array (matriz) discount para sumarlo al array (matriz) prices
prices = np.random.randint(100, 500, size=(3,3))
discount = np.array([10, 20, 30])
discount_prices = prices + discount
print(prices, "\n")
print(discount_prices)

[[199 231 374]
 [401 318 324]
 [174 298 208]] 

[[209 251 404]
 [411 338 354]
 [184 318 238]]


In [8]:
# concatenacion
array_a  = np.array([1,2,3])
array_b  = np.array([4,5,6])
concatenate_a = np.concatenate((array_a, array_a))
print(concatenate_a)
concatenate_ab = np.concatenate((array_a, array_b))
print(concatenate_ab)


[1 2 3 1 2 3]
[1 2 3 4 5 6]


In [10]:
# stacking apilación de arrays verticalmente
stacked_vertical = np.vstack((array_a, array_b))
print(stacked_vertical)

[[1 2 3]
 [4 5 6]]


In [11]:
# stacked apilación de arrays horizontalmente
stacked_horizontal = np.hstack((array_a, array_b))
print(stacked_horizontal)

[1 2 3 4 5 6]


In [14]:
# split división de arrays
array_c = np.arange(1, 10)
split_array = np.split(array_c, 3) # split división de array en partes de 3 elementos
print(array_c, " \n")
print(split_array)


[1 2 3 4 5 6 7 8 9]  

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
